### ISSUE TITLE
Project name invokes suicidal thoughts on the reader.

### ISSUE THREAD

**Issue by Skorezore** [nmai/layr#2]
When I read *layr*, I almost instantly get the urge to shoot myself in the head to put a quick end to suffering. I suggest the name *layr* be replaced with something sensible.

**Comment by nmai** [comment]
Thanks for the feedback Julian. Do you have any (sensible) suggestions?

**Comment by Skorezore** [comment]
Potato, but it's pronounced potahto.

**Comment by nmai** [comment]
That's a great suggestion, but unfortunately I am already using that name for separate project.
